plugins {
    id 'java'
    alias(libs.plugins.dependencyManagement)
}

group = 'RuyiBang'
version = '1.0.0'
description = 'OttPlatform Core Starter for logging, UUID, exception handling'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    // Spring Boot
    implementation(libs.springBootWeb)
    implementation(libs.springBootSecurity)

    // JWT
    implementation(libs.jjwtApi)
    runtimeOnly(libs.jjwtImpl)
    runtimeOnly(libs.jjwtJackson)

    // Logging
    implementation(libs.logbackClassic)
    implementation(libs.logstash)

    // Tests
    testImplementation(libs.springBootTest)
}

tasks.named('test') {
    useJUnitPlatform()
}
