plugins {
    id 'java-library'
    alias(libs.plugins.dependencyManagement)
    id 'maven-publish'
}

group = 'org.ruyibang'
version = (findProperty("projectVersion") ?: "0.0-SNAPSHOT")
description = 'OttPlatform Core Starter for logging, UUID, exception handling'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    // Spring Boot
    implementation platform("org.ruyibang:ottplatform.root:0.0")
    annotationProcessor platform("org.ruyibang:ottplatform.root:0.0")
    implementation(libs.springBootWeb)
    implementation(libs.springBootSecurity)

    implementation "org.apache.commons:commons-lang3"

    // JWT
    implementation "io.jsonwebtoken:jjwt-api"
    runtimeOnly "io.jsonwebtoken:jjwt-impl"
    runtimeOnly "io.jsonwebtoken:jjwt-jackson"

    // Logging
    implementation "net.logstash.logback:logstash-logback-encoder"

    compileOnly "org.projectlombok:lombok"
    annotationProcessor "org.projectlombok:lombok"

    // Tests
    testImplementation(libs.springBootTest)
}

tasks.named('test') {
    useJUnitPlatform()
}
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = 'org.ruyibang'
            artifactId = 'ottplatform.core'   // <<< change: no dots
            version = project.version
        }
    }
    repositories {
        // mavenLocal()   // optional; you can remove it for CI
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/Ruyi-Bang/packages")
            credentials {
                username = findProperty("githubUsername") ?: System.getenv("GPR_USER")
                password = findProperty("githubToken")    ?: System.getenv("GPR_KEY")
            }
        }
    }
}
